server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 49.232.110.103:22122



mingrui:
  upload:
    path:
      windows: D:\\images
      linux: /hh/images
    img:
      host: http://49.232.110.103/


